the_store/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('apply-coupon/', views.coupon_apply, name='coupon_apply'),
]

the_store/main/urls.py
from django.contrib import admin
from django.urls import path, include
from store.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', Register.as_view(), name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

the_store/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('<int:order_id>/', views.detail, name='detail'),
]

the_store/store/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from .views import *

app_name = 'store'

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('category/', category_show, name='category_show'),
    path('category/<slug:slug>/', category_show, name='category_filter'),
    path('detail/<slug:slug>/', product_detail, name='product_detail'),
]

the_store/cart/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


class Coupon(models.Model):
    code = models.CharField(max_length=30, unique=True)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.code

the_store/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range (1,6)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)


class CouponApplyForm(forms.Form):
    code = forms.CharField()


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

the_store/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .forms import CartAddProductForm, CouponApplyForm
from cart.utils.cart import Cart
from store.models import Product
from django.views.decorators.http import require_POST

from .models import Coupon


def detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity':item['quantity'],
                                                                   'update': True})
    coupon_apply_form = CouponApplyForm()
    return render(request,
                  'cart/detail.html',
                  {'cart': cart,
                   'coupon_apply_form': coupon_apply_form})


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        data = form.cleaned_data
        cart.add(product=product, 
                 quantity=data['quantity'],
                 update_quantity=data['update'])
    return redirect('cart:detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')


@require_POST
def coupon_apply(request):
    now = timezone.now()
    form = CouponApplyForm(request.POST)
    if form.is_valid():
        code = form.cleaned_data['code']
        try:
            coupon = Coupon.objects.get(code__iexact=code,
                                        valid_from__lte=now,
                                        valid_to__gte=now,
                                        status=True)
            request.session['coupon_id'] = coupon.id
        except Coupon.DoesNotExist:
            request.session['coupon_id'] = None
    return redirect('cart:detail')

the_store/cart/templates/cart/detail.html
<!DOCTYPE html>
<html lang="en">
  {% extends 'base.html'%}
  {% load static %}

  {% block title %}
  Корзина покупок
  {% endblock title %}

  {% block content %}


  <!--================Cart Area =================-->
  <section class="cart_area">
      <div class="container">
          <div class="cart_inner">
              <div class="table-responsive">
                  <table class="table">
                      <thead>
                          <tr>
                              <th scope="col">Назва</th>
                              <th scope="col">Ціна</th>
                              <th scope="col">Кількість</th>
                              <th scope="col">Сума</th>

                          </tr>
                      </thead>
                      {% for item in cart %}
                      <tbody>
                          <tr>
                              <td>
                                  <div class="media">
                                      <div class="d-flex">
                                          <img src="{{ item.product.image_url }}" width="100px" height="100px" alt="">
                                      </div>
                                      <div class="media-body">
                                          <p>{{ item.product }}</p>
                                      </div>
                                  </div>
                              </td>
                              <td>
                                  <h5>${{ item.price }}</h5>
                              </td>
                              <td>


                                    <form action="{% url 'cart:cart_add' item.product.id %}" method="post">
                                    {{ item.update_quantity_form.quantity }}

                                    {{ item.update_quantity_form.update }}

                                        <button type="action" class="btn btn-outline-secondary">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="currentColor" class="bi bi-arrow-repeat" viewBox="0 0 16 16">
                                        <path d="M11.534 7h3.932a.25.25 0 0 1 .192.41l-1.966 2.36a.25.25 0 0 1-.384 0l-1.966-2.36a.25.25 0 0 1 .192-.41zm-11 2h3.932a.25.25 0 0 0 .192-.41L2.692 6.23a.25.25 0 0 0-.384 0L.342 8.59A.25.25 0 0 0 .534 9z"></path>
                                        <path fill-rule="evenodd" d="M8 3c-1.552 0-2.94.707-3.857 1.818a.5.5 0 1 1-.771-.636A6.002 6.002 0 0 1 13.917 7H12.9A5.002 5.002 0 0 0 8 3zM3.1 9a5.002 5.002 0 0 0 8.757 2.182.5.5 0 1 1 .771.636A6.002 6.002 0 0 1 2.083 9H3.1z"></path>
                                        </svg></button></div>

                                        {% csrf_token %}
                                        </form>

                              </td>

                              <td>
                                  <h5>${{ item.total_price }}</h5>
                                  <td>
                                <a href="{% url 'cart:cart_remove' item.product.id %}" class="btn btn-outline-danger">Видалити</a>
                              </td>
                              </td>



                              {% endfor %}
                          </tr>
               


                          <tr class="bottom_button">
 {% if cart.coupon %}
                              <td>
Ви успішно активували купон "{{ cart.coupon.code }}"
                              </td>
                              <td>
Ваша знижка {{ cart.coupon.discount }}%

                              </td>
                              <td>
Попередня сума ${{ cart.get_total_price }}
                              </td>

                              <td>
- ${{ cart.get_discount|floatformat:"2" }}
                              </td>
                              <td>
{% endif %}
                              </td>
                          </tr>
                          <tr>
<td>
    {% if user.is_authenticated %}
    {% if not cart.coupon %}
<form action="{% url 'cart:coupon_apply' %}" method="post">

    <input type="text" class="form-control" name="code" required="" placeholder=" код на знижку вводити тут" onfocus="this.placeholder = 'якщо робочий то запрацює, якщо ні то ні'" onblur="this.placeholder = ' код на знижку '" id="id_code">
{% endif %}
    {% endif %}
                                      {% csrf_token %}
</td>

                            <td>
{% if not cart.coupon %}{% if user.is_authenticated %}

<button type="submit" class="btn btn-dark btn-rounded"><i class="fas fa-check text-dark rounded-circle bg-white mr-1" style="padding: 7px;"></i> SALE</button></form>

{% endif %}
                              {% endif %}

                              <td>
                                  {% if user.is_authenticated %}<h5>Загальна сума</h5>{% endif %}
                              </td>

                              <td>
                                  <h5>${{ cart.get_total_price_after_discount|floatformat:"2" }}</h5>
                              </td>
                              <td>

                              </td>
                          </tr>

                          <tr class="out_button_area">
                              <td class="d-none-l">


                              </td>

                              <td class="">


<td>

                              </td>


 </td>
                              <td>

                              </td>

                              <td>

                                  <div class="checkout_btn_inner d-flex align-items-center">

                                      <a class="gray_btn" href="{% url 'store:category_show' %}">Продовжити покупки</a>
                                      {% with total_items=cart|length %}
                                        {% if cart|length > 0 %}
                                      <a class="primary-btn ml-2" href="{% url 'orders:order_create' %}">Оформити</a>
                                      {% endif %}
                                      {% endwith %}
                                  </div>
                              </td>
                          </tr>
                      </tbody>
                  </table>
              </div>
          </div>
      </div>
  </section>
  <!--================End Cart Area =================-->
  {% endblock content %}